spring:
  output:
    ansi:
      enabled: always
---
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test;MODE=MySql;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true

    hibernate:
      ddl-auto: create